### PR TITLE
Adds publishing jobs

### PR DESCRIPTION
**Pull request by claudiubelu**
Adds the ``publish_images.yaml`` workflow, which will run everyday or when manually dispatched.

If there is a new release that was not yet published on Charmhub, it will upload the respective FINOS Legend Engine, SDLC, and Studio images into Charmhub and make a release. It will also create a new release on latest. This workflow will then trigger ``create_release.yaml``.

Adds the ``create_release.yaml`` workflow, which can also be manually triggered.

This workflow will create a new branch with the given release name, and creates a commit in which it updates the ``bundle.yaml`` file to have the Legend Engine, SDLC, Studio charms point towards the given release channel. The workflow will then
publish the new bundle in Charmhub under ``$release/edge``.

The following Secrets need to be added (Settings > Actions > New repository secret):

- ``CHARMCRAFT_AUTH``: needed to upload the FINOS Legend images, upload the bundle, release the charms and bundle.
- ``GH_TOKEN``: needed to chain the 2 workflows mentioned above.

### CODE REVIEW

**Comment by claudiubelu** [comment]
@jnsgruk , can you take a look and see if it looks good to you?

**Comment by jnsgruk** [comment]
Is there a reason we're not using the `charming-actions` stuff?

**Comment by claudiubelu** [comment]
> Is there a reason we're not using the `charming-actions` stuff?

``charming-actions`` contains actions to build and publish charms, and build and publish bundles. It doesn't quite fit what we're trying to do here: we're not building new charm revisions, we're just uploading image resources and creating a charm release with a charm revision with the latest charm revision that was already uploaded.

Ideally, ``charming-actions`` would have an option to just upload the image and release the Charm with the charm's latest revision and image's latest revision.

**Comment by jnsgruk** [comment]
> > Is there a reason we're not using the `charming-actions` stuff?
> 
> `charming-actions` contains actions to build and publish charms, and build and publish bundles. It doesn't quite fit what we're trying to do here: we're not building new charm revisions, we're just uploading image resources and creating a charm release with a charm revision with the latest charm revision that was already uploaded.
> 
> Ideally, `charming-actions` would have an option to just upload the image and release the Charm with the charm's latest revision and image's latest revision.

@simmskj I guess you're already tracking this, but perhaps a use-case for charming-actions one day.

In the mean time, I'll get this merged in. Thanks @claudiubelu :)

**Pull request merged**
